#!/bin/bash
#SBATCH -A mp309
#SBATCH -C gpu
#SBATCH -q regular
#SBATCH -t 00:10:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-task=1
#SBATCH --cpus-per-task=10
#SBATCH --gpu-bind=none
#SBATCH -J nvshmem-test
#SBATCH -o output.%j

module load cuda
module load nvshmem

./spgemm
# srun -n 8 --gpus-per-task=1 ./spgemm
